[package]
name = "little_weirdo"
version = "0.1.4"
edition = "2021"
authors = ["Daniël⚡ <daniel@hi-squeaky-things.nl>"]
description = "A Rust #no-std optimized wave table synthesizer for embedded devices."
license = "MIT"
repository = "https://github.com/hi-squeaky-things/little-weirdo"
keywords = ["no-std", "synthesizer", "wavetable"]
categories = ["embedded"]

[workspace]
resolver = "2"

[lib]
name = "little_weirdo"

[dependencies]
array-init = "2.1.0"
rand = { version = "0.10.2", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["alloc"] }
postcard = "1.1.3"


[dev-dependencies]
hound = "3.5.1"
cpal = "0.17.1"
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
console = "0.16.4"
midir = "0.11.0"
midi-control = "0.2.3"
serde_json = "1.0.151"
criterion = "0.8.2"
embedded-storage = "0.3.1"
embassy-embedded-hal = "0.6.0"
link_args = { version = "0.6.0", default-features = false }
tokio = { version = "1.53.1", features = ["full"] }
embassy-sync = "0.8.0"
soundfont = "0.1.0"
embedded-io-cursor = { version = "0.1.0", features = ["std"] }
embedded-io = { version = "0.7.1", features = ["std"] }

[[bench]]
name = "synth_benchmark"
harness = false
