//! WaveTableOscillator to generate sounds using Wavetable synthesis.

use crate::synth::data::waveforms::BoxedWaveforms;

use super::data::waveforms::{Waveforms};
use super::math::percentage;
use super::Clockable;
use rand::rngs::SmallRng;
use rand::{RngExt, SeedableRng};

use serde::Deserialize;
use serde::Serialize;

extern crate alloc;
use alloc::sync::Arc;

/// Configuration for low-frequency waveform oscillator
#[derive(Copy, Clone, Serialize, Deserialize)]
pub struct WaveformLFOConfig {
    /// Index of the soundbank to use for waveform generation
    pub soundbank_index: u8,
    /// Time parameter for LFO operations (in 100x seconds)
    pub time: u16,
}

/// Configuration for standard waveform oscillator
#[derive(Copy, Clone, Serialize, Deserialize)]
pub struct WaveformOscillatorConfig {
    /// Index of the soundbank to use for waveform generation
    pub soundbank_index: u8,
    /// Whether to enable frequency glide (smooth frequency transitions)
    pub glide: bool,
    /// Rate of frequency glide (0 to 255, higher values = faster glide)
    pub glide_rate: u8,
    /// Detune amount in semitones (-128 to 127)
    pub detune: i8,
    /// Frequency detune amount in Hz (-128 to 127)
    pub freq_detune: i8,
    // Use a grain oscillator.
    pub grains: bool,
    // List of grains used
    pub grains_seq: [u8; 8],
}

/// WaveformOscillator generates audio signals using waveform (sample) synthesis
/// This oscillator supports both standard audio rate oscillators and low-frequency oscillators
pub struct WaveformOscillator {
    /// Configuration settings for this oscillator instance
    pub config: WaveformOscillatorConfig,

    /// Current phase position in the waveform (0 to loop_end)
    phase: u16,

    /// End point of the waveform loop (determines period length)
    loop_end: u16,

    /// Flag indicating whether frequency has changed and needs processing
    freq_changed: bool,

    /// Random number generator for noise generation
    random: SmallRng,

    /// Sample rate of the audio system (used for frequency calculations)
    sample_rate: u16,

    /// Lookup table for converting phase to waveform indices
    lookup_table: [u16; 3000],

    /// Target frequency for glide operations
    target_freq: u16,

    /// Original frequency before any detuning
    original_freq: u16,

    /// Step size for frequency glide calculations
    freq_step: i16,

    /// Current actual frequency being used for playback
    current_freq: u16,

    /// Speed factor for sample processing (controls how often we process samples)
    speed: u16,

    /// Last output value generated by the oscillator
    last_output: i16,

    /// Counter for tracking when to process next sample
    speed_count: u16,

    /// Shared reference to the waveforms data structure
    waveforms: Arc<BoxedWaveforms>,

    /// Waveform pointer, points to the grain being selected
    waveform_pointer: u8,

    grain_selector: u8,
}

impl Clockable for WaveformOscillator {
    fn clock(&mut self, _sample: Option<i16>) -> i16 {
        self.speed_count += 1;
        if self.speed == self.speed_count {
            self.speed_count = 0;

            // Reset phase when reaching end
            if self.phase == self.loop_end {
                self.phase = 0;
                if self.config.grains {
                    self.grain_selector = (self.grain_selector + 1) & 0x7; // Fast modulo 8
                    self.waveform_pointer = self.config.grains_seq[self.grain_selector as usize];

                    // end of grains
                    if self.waveform_pointer == 255 {
                        self.grain_selector = 0;
                        self.waveform_pointer =
                            self.config.grains_seq[self.grain_selector as usize];
                    }
                }

                // Handle frequency changes
                if self.freq_changed {
                    if self.current_freq != self.target_freq {
                        let diff = self.target_freq as i16 - self.current_freq as i16;
                        let step_size = self.freq_step;

                        if diff.abs() < step_size.abs() {
                            self.current_freq = self.target_freq;
                            self.freq_changed = false;
                        } else {
                            self.current_freq = (self.current_freq as i16 + step_size) as u16;
                        }
                    } else {
                        self.freq_changed = false;
                    }

                    self.loop_end = self.sample_rate / self.current_freq;
                    self.calculate_lookup_table();
                }
            }

            // Generate output
            let output = match self.config.soundbank_index {
                255 => {
                    // Random noise
                    self.random
                        .random_range((i16::MIN + 1000)..(i16::MAX - 1000))
                }
                _ => {
                    // Wavetable lookup
                    let index = self.lookup_table[self.phase as usize] as usize;
                    self.waveforms
                        .get_waveform_reference(self.waveform_pointer)[index]
                }
            };

            self.phase += 1;
            self.last_output = output;
        }

        self.last_output
    }
}

impl WaveformOscillator {
    /// Creates a new low-frequency oscillator instance
    /// Used for modulation effects like LFOs
    pub fn new_lfo(
        config: WaveformLFOConfig,
        sample_rate: u16,
        waveforms: Arc<BoxedWaveforms>,
    ) -> Self {
        let new_config = WaveformOscillatorConfig {
            soundbank_index: config.soundbank_index,
            glide: false,
            glide_rate: 0,
            detune: 0,
            freq_detune: 0,
            grains: false,
            grains_seq: [0; 8],
        };
        let mut osc = Self::new(new_config, sample_rate, waveforms);
        osc.speed = 4 * config.time;
        osc
    }

    pub fn new(
        config: WaveformOscillatorConfig,
        sample_rate: u16,
        waveforms: Arc<BoxedWaveforms>,
    ) -> Self {
        let mut osc = Self {
            config,
            phase: 0,
            loop_end: sample_rate / 440 + 1,
            freq_changed: false,
            random: SmallRng::seed_from_u64(23702372039u64),
            sample_rate,
            lookup_table: [0u16; 3000],
            target_freq: 440,
            original_freq: 440,
            current_freq: 440,
            freq_step: 0,
            last_output: 0,
            speed_count: 0,
            speed: 1,
            waveforms,
            waveform_pointer: config.soundbank_index,
            grain_selector: 0,
        };
        if config.grains {
            osc.waveform_pointer = config.grains_seq[osc.grain_selector as usize];
        }
        osc.calculate_lookup_table();
        osc
    }

    fn calculate_lookup_table(&mut self) {
        let sample_rate_expanded: u32 = self.sample_rate as u32 * 10_000;
        let one_loop: u32 = sample_rate_expanded / self.current_freq as u32;
        let one_step_loop: u32 = one_loop / 600;
        let steps: u16 = self.sample_rate / self.current_freq;

        for i in 0..steps {
            // Direct calculation: (i * 10_000) / one_step_loop
            self.lookup_table[i as usize] = ((i as u32 * 10_000) / one_step_loop) as u16;
        }
    }

    /// Reset internal state to default values
    fn reset_state(&mut self) {
        self.phase = 0;
        self.freq_changed = false;
        self.target_freq = 440;
        self.original_freq = 440;
        self.current_freq = 440;
        self.freq_step = 0;
        self.last_output = 0;
        self.speed_count = 0;
        self.speed = 1;
        self.grain_selector = 0;
    }

    /// Reload configuration
    pub fn reload(&mut self, config: WaveformOscillatorConfig) {
        self.config = config;
        self.reset_state();
        self.waveform_pointer = config.soundbank_index;

        if self.config.grains {
            self.waveform_pointer = config.grains_seq[self.grain_selector as usize];
        }
        self.calculate_lookup_table();
    }

    pub fn reload_lfo(&mut self, config: WaveformLFOConfig) {
        let new_config = WaveformOscillatorConfig {
            soundbank_index: config.soundbank_index,
            glide: false,
            glide_rate: 0,
            detune: 0,
            freq_detune: 0,
            grains: false,
            grains_seq: [0; 8],
        };
        self.reset_state();
        self.waveform_pointer = config.soundbank_index;
        self.speed = 4 * config.time;
        self.config = new_config;
        self.calculate_lookup_table();
    }

    /// Manipulate frequency with percentage
    pub fn manipulate_freq(&mut self, perc: u8, amount: u16) {
        self.current_freq = self.original_freq + percentage(amount as i16, perc as i16) as u16;
        self.freq_changed = true;
    }

    /// Change frequency with optional glide
    pub fn change_freq(&mut self, frequency: u16) {
        if self.current_freq != frequency {
            self.target_freq = frequency;

            if self.config.glide {
                let diff = frequency as i16 - self.current_freq as i16;
                self.freq_step = diff / self.config.glide_rate as i16;
                // Ensure non-zero step
                if self.freq_step == 0 {
                    self.freq_step = diff / 2;
                }
            } else {
                self.current_freq = frequency;
            }

            self.original_freq = frequency;
            self.freq_changed = true;
        }
    }
}
