@startuml
title LttL Weirdo Synth design
:EVERY_SAMPLE;
start
    split
       #LightBlue:OSC1;
       #LightBlue:ENV1;
       :GAIN1;
    split again
        #LightBlue:OSC2;
        #LightBlue:ENV2;
        :GAIN2;
    split again
        #LightBlue:OSC3;
        #LightBlue:ENV3;
        :GAIN3;
    end split
        :MIX (+);
if (Filter Enabled) equals (Yes)  then
   #LightBlue:FILTER;
else (No)
endif

:GAIN-MAIN;

if (Overdrive Enabled) equals (Yes) then
   #LightBlue:OVERDRIVE;
else (No)
endif

:SAMPLE_OUT;

end
@enduml

